export default [
    {
        id: 1,
        type: 'posto',
        name: 'Hospital Municipal de Salvador HMS',
        endereco: 'R. Ver. Zezéu Ribeiro, s/n - Cajazeiras',
        especialidade: 'Unidade basica de saude',
        estado:'Bahia',
        cidade: 'Salvador',
        cep: '',
    },
    {
        id: 2,
        type: 'posto',
        name: 'CS Nelson Piauhy Dourado',
        endereco: 'Rua Endeo Nascimento, Qd. C, s/n, Caj. III, Água Claras',
        especialidade: 'Unidade basica de saude',
        estado:'Bahia',
        cidade: 'Salvador',
        cep: '',
        
    },
    // {
    //     id: 3,
    //     type: 'posto',
    //     name: 'CS Engenho velho da Federação',
    //     endereco: 'Rua: Apolinario Santana - Engenho velho da Federação',
    //     especialidade: 'Unidade basica de saude',
    //     estado:'Bahia',
    //     cidade: 'Salvador',
    //     cep: '',
    // },
    // {
    //     id: 4,
    //     type: 'posto',
    //     name: 'CS Sete de Abril',
    //     endereco: 'Rua Feliciano, s/n - Sete de Abril ( ponto de referencia 50ª CPM)',
    //     especialidade: 'Unidade basica de saude',
    //     estado:'Bahia',
    //     cidade: 'Salvador',
    //     cep: '',
    // },
]